# Label PRs based on file paths
# Used by actions/labeler

# Source code changes
rust:
  - changed-files:
      - any-glob-to-any-file: 'src/**/*.rs'

# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**/*'

# CI/CD changes
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'Cargo.toml'
          - 'Cargo.lock'

# Tests
tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**/*'
          - 'benches/**/*'
